### ISSUE TITLE
`flask_script` deprecated

### ISSUE THREAD

**Issue by ChiatzenW** [miguelgrinberg/flasky-first-edition#4]
Hello, I know this repo is deprecated but just want to point out that it seems that `flask_script` is no longer maintained and there is a bug when importing, it will import `flask._compact` instead of `flask_script._compact`.

**Comment by miguelgrinberg** [comment]
If you are going to use this project you need to stick to versions of dependencies from the time. You cannot expect that the project will continue to work with up to date dependencies. Using the requirements file for versions is probably a good idea. You should also stay on an older Python version such as 3.6/3.7, as new versions might also introduce incompatibilities.
